-module(logs_schema).
-export([get/0]).

-include_lib("apptools/include/config_schema.hrl").

get() ->
    [{logs,
      [{daemon,
        [{enabled,
          #json_type{name = bool, typical = true}},
         {filter,
          [{show,
            [#json_type{name = atom, typical = '*'}]},
           {hide,
            [#json_type{name = atom, typical = '*'}]}]},
         {tty,
          #json_type{name = bool, typical = false}},
         {file,
          [{enabled,
            #json_type{name = bool, typical = true}},
           {path,
            #json_type{name = writable_file,
                       typical = <<"daemon.log">>}}]}]},
       {dbg,
        [{enabled,
          #json_type{name = bool, typical = true}},
         {filter,
          [{show,
            [#json_type{name = atom, typical = '*'}]},
           {hide,
            [#json_type{name = atom, typical = '*'}]}]},
         {tty,
          #json_type{name = bool, typical = false}},
         {file,
          [{enabled,
            #json_type{name = bool, typical = true}},
           {path,
            #json_type{name = writable_file,
                       typical = <<"dbg.log">>}}]}]},
       {error,
        [{enabled,
          #json_type{name = bool, typical = true}},
         {tty,
          #json_type{name = bool, typical = true}},
         {file,
          [{enabled,
            #json_type{name = bool, typical = true}},
           {path,
            #json_type{name = writable_directory,
                       typical = <<"./">>}}]}]}]}].
